[project]
name = "library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Usman GM", email = "muhammadusman75425965etc@gamil.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.2",
]

[project.scripts]
library = "library:main"
app = "library:script.app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
